open-edge-platform/edge-microvisor-toolkit-standalone-node

requirements.txt
=> Cleaned up requirement.txt

.github/workflows/auto-add-labels.yml, .github/workflows/auto-close.yml, .github/workflows/auto-update.yml, .github/workflows/post-merge-standalone-node.yaml, .github/workflows/pre-merge.yml
=> chore: fix zizmor findings

.github/workflows/auto-update.yml, .github/workflows/post-merge-standalone-node.yaml, .github/workflows/pre-merge.yml
=> chore: sort all zizmor findings

.github/workflows/post-merge-standalone-node.yaml
=> chore: add secret for teams notification

standalone-node/emt_uos/download_emt_ous_with_custom_scripts.sh
This PR is to update the emt-uos download path from non-auth rs server
=> emt-uos repo url update for downloading

standalone-node/installation_scripts/config-file, standalone-node/provisioning_scripts/enable-dmv.sh, standalone-node/provisioning_scripts/install-os.sh
These changes to configure the lvm partition for single hdd as per the user wish.  user can choose lvm to zero to utilize the max disk space to persistent volume if its not use.
ADR link: https://github.com/open-edge-platform/edge-microvisor-toolkit-standalone-node/pull/78/files
=> update dm-verity to create lvm based on user input

standalone-node/cluster_installers/docs/standalone-edge-node-installer.md, standalone-node/cluster_installers/sen-k3s-installer.sh
Removes checks for calico specific namespaces to be present
Fixes issue waiting for namespaces
Using resized virtualbox vhd
=> fix: remove namespace and fix docs

standalone-node/installation_scripts/bootable-usb-prepare.sh, standalone-node/installation_scripts/build-emt-s-install-pkg.sh, standalone-node/installation_scripts/standalone-vm-setup.sh, standalone-node/provisioning_scripts/install-os.sh, standalone-node/provisioning_scripts/os-partition.sh
These changes to run the standalone node (EMT-S) as a virtual edge node. Developer or User can quickly test the changes without waiting for the real hardware.
It will speed up the development life cycle and reduce the dependency on the real hardware.
=> stanalone vm support for developers

standalone-node/docs/prepare_bootable_usb_windows.md
Adding instructions on how to prepare a bootable USB drive for Edge Microvisor Toolkit Standalone Node, using Hyper-V Virtual Machine on Windows
=> Guide on using Ubuntu VM in Hyper-V to create bootable USB.

standalone-node/cluster_installers/readme.md, standalone-node/cluster_installers/sen-k3s-installer.sh
Remove `--flannel-backend=none` and enable flannel by default. Add user guide how to disable flannel to use different CNIs.
=> chore: enable flannel by default

standalone-node/cluster_installers/sen-k3s-installer.sh, standalone-node/provisioning_scripts/cloud-init.yaml, standalone-node/provisioning_scripts/k3s-configure.sh
Moves k3s install logic to a separate script that could-init calls. Also changes log output to tty1 in keeping with changes from @shankarsrinivas1
=> feat: add wrapper script and change logging

README.md
Fixed broken link to Contribution Guide in README.md
None
Documentation only change.
=> Fixed broken link to Contribution Guide in README.md

standalone-node/docs/user-guide/Get-Started-Guide.md
=> docs: Add note about alias

standalone-node/installation_scripts/bootable-usb-prepare.sh, standalone-node/installation_scripts/build-emt-s-install-pkg.sh, standalone-node/installation_scripts/config-file, standalone-node/installation_scripts/standalone-vm-setup.sh, standalone-node/installation_scripts/user-apps/readme.md, standalone-node/provisioning_scripts/install-os.sh
These changes to copy the custom user-app folder to EMT node. user can configure these custom user-aps in custom cloud-init section as per their need.
=> custom user-apps setup on Edge node

standalone-node/docs/user-guide/desktop-virtualization-cloud-init.md, standalone-node/docs/user-guide/pre-loading-user-apps.md, standalone-node/installation_scripts/user-apps/readme.md
=> Adding script to apply custom network attachment definition for secondary interface

standalone-node/installation_scripts/standalone-vm-setup.sh, standalone-node/provisioning_scripts/install-os.sh
This PR is to delete the existing boot entries pileup in bios menu and create a new boot entry to boot directly to hard disk after successful provision 
=> Boot entry creationfor boot from disk directly

standalone-node/installation_scripts/standalone-vm-setup.sh
syntax error correct for standalone-vm-setup.sh
=> Fix for vm launch

standalone-node/docs/user-guide/desktop-virtualization-cloud-init.md
Fixes # (issue) PR to fix issue with cloud-init networking section
No
Code review
=> Fix cloud init networking

standalone-node/docs/user-guide/desktop-virtualization-image-guide.md
Creating a user guide for EMT IDV image
No
Code review
=> Idv doc update

standalone-node/docs/user-guide/desktop-virtualization-image-guide.md
Adding block diagram 
No
Code review
=> Idv doc diagram

standalone-node/docs/user-guide/desktop-virtualization-image-guide.md
=> Fix block diag

standalone-node/docs/user-guide/index.rst
Update index for dcumentation
No
Code review. Doc update.
=> Update index for dcumentation

standalone-node/emt_uos/download_emt_ous_with_custom_scripts.sh
Updating the EMT/EMB uOS to latest available in the fileserver.
=> Updating the EMT bootkit uOS to latest available in file server

standalone-node/docs/user-guide/Get-Started-Guide.md, standalone-node/docs/user-guide/emt-update-guide.md, standalone-node/installation_scripts/download_images.sh
Documents how image download script works
=> feat: image download docs

standalone-node/host_os/download_tmv.sh
Removed commented code from scripts
Remove the commented code from the scripts. As per earlier review comments.
=> Remove the commented code from the scripts.

standalone-node/docs/user-guide/desktop-virtualization-image-guide.md
- Also set the right permission for the device, which is hot plugged.
On hot plug of device, the owner and root of the device where getting changed.
This fix will make sure the qemu:qemu owns the device with required permissions.
None
=> [Fix]: [USB device] On hot plug, make sure qemu:qemu owns the device 
